ALTER TABLE quiz_run ADD COLUMN run_state VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE quiz_run ADD COLUMN creation_date TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE quiz_run ADD COLUMN completion_date TIMESTAMP NULL;